module.exports = [
  { id: 'name', title: 'Name' },
  { id: 'about', title: 'About' },
  { id: 'website', title: 'Website' },
  { id: 'location', title: 'Location' },
  { id: 'language', title: 'Language' },
  { id: 'expertise', title: 'Expertise' },
  { id: 'technology expertise', title: 'Technology Expertise' },
  { id: 'business segment', title: 'Business Segment' },
  { id: 'industry focus', title: 'Industry Focus' },
  { id: 'organizational size', title: 'Organizational Size' },
  { id: 'awards', title: 'Awards' },
  { id: 'clients', title: 'Clients' },
  { id: 'certification', title: 'Certification' },
  { id: 'team', title: 'Team' },
  { id: 'typical hourly rate', title: 'Hourly Rate' },
  { id: 'year founded', title: 'Year Founded' },
  { id: 'addresses and working hours', title: 'Addresses / Working Hours' },
  { id: 'contact email', title: 'Email' },
  { id: 'phone', title: 'Phone' },
  { id: 'facebook', title: 'Facebook' },
  { id: 'twitter', title: 'Twitter' },
  { id: 'linkedin', title: 'Linkedin' },
  { id: 'google+', title: 'Google+' },
  { id: 'score', title: 'Score' },
  { id: 'membershipLevel', title: 'Membership Level' },
]